### ISSUE TITLE
feat(trace): isolate damaged directory artifacts without hiding healthy runs

### ISSUE THREAD

**Issue by andreasronge** [andreasronge/ptc_runner#1654]
## Parent and scope

- Parent: #1650
- Viewer refresh and request-time private authorization remain owned by #1578.
- Exact selected-run capture introduced by #1653 remains a separate source path.
- This issue changes whole-directory admission only. It does not implement trace persistence (#1655), repair files, or broaden filesystem authority.

## Evidence reviewed on `origin/main`

Research used fetched `origin/main` at `31064232` (which contains merged #1653 at `8032a4a9` / `a0c79b81`).

- `TraceLog.load/1` currently lists every supported suffix, sorts filenames, flattens all decoded events, and validates one aggregate. Filenames disappear before identity/lifecycle validation, so ordinary directory loading accidentally accepts a run split across files.
- `TraceLog.capture_directory/2` inventories and verifies the directory immutably, then `decode_capture_sources/1` rejects one run appearing in two files, but still accepts arbitrary names and multiple runs in one file.
- `TraceSnapshot` delegates directory capture to that function and reuses `TraceLog` queries. Viewer directory discovery is a `TraceSnapshot` held by `ViewerSnapshotStore`.
- #1653's `SelectedCanonicalSource` opens only `<run-ref>.jsonl` or `<run-ref>.private.jsonl`, proves the embedded run/trace identity, and ignores unrelated files and directory/file-count limits. Its source identity is intentionally distinct from whole-directory capture.
- Every directory producer binds the destination to the run identity: command publication uses `<run-ref>[.private].jsonl`; analysis sessions use `<analysis-run-id>.jsonl`; `SessionTrace` validates `<run-id>.jsonl`. The CLI and project-file references document that layout.
- Contrary evidence is not a required directory contract: tests often use names such as `trace.jsonl` and `runs.jsonl` for fixture convenience, including 40 runs in one file; `examples/viewer-demo/run.sh` renames generated command traces to journey names. Those must be updated. No retained operator guide promises arbitrary names or split runs for directory discovery.
- Explicit single-file sources are intentional and remain distinct: the public source contract grants one JSONL file, and `ptc repl --trace trace.jsonl` is documented. Such a file may remain an aggregate of complete runs because it is explicitly selected rather than discovered as a canonical directory member.
- History supports narrowing rather than compatibility machinery: immutable capture was introduced in `2df38417` by layering inventory around the already permissive directory loader; it did not define filename/run semantics. #1653 explicitly kept exact selection separate and whole-directory fail-closed pending this work.
- Current hard bounds are 4,096 directory entries, 1,024 selected trace files, 8,000,000 aggregate source bytes, 32,000,000 retained snapshot bytes, and 1,000,000 result bytes. Direct directory loading currently lacks the first two bounds and immutable mutation proof.

This is a 0.x library. The fixture/demo uses do not justify a manifest, compatibility reader, or dependency graph for split histories.

## Frozen canonical directory contract

A generated trace directory is a set of filename-bound canonical files:

- sanitized: `<run-id>.jsonl`;
- private: `<run-id>.private.jsonl`.

For directory admission, one selected file contains events for exactly one run ID and exactly one trace ID. Its embedded run ID must equal the filename stem after removing the class suffix. The trace ID is embedded, not encoded in the filename. Across admitted files, run ID and trace ID remain one-to-one. A run may be open or terminal under the existing lifecycle rules, but its entire available history is in that one file.

### Canonical basename grammar

Directory discovery examines raw basename bytes ending in `.jsonl` or `.private.jsonl`, but a canonical filename claim exists only when the suffix-stripped stem matches `\A[A-Za-z0-9][A-Za-z0-9._-]{0,255}\z`. This is a 1–256-byte ASCII run ID, excludes `.` / `..`, separators, NUL, control characters, and invalid UTF-8, and covers every current command, analysis-session, and session-trace producer. The embedded event ID still passes the existing 1–256-byte valid-UTF-8 event rule; directory admission additionally requires exact equality with the canonical ASCII stem.

A suffix-selected basename outside this grammar is not ignored. It becomes a node with `invalid_filename`, has no filename run claim, and may still connect to other nodes through fully decoded embedded run/trace claims. Raw basenames are sorted by unsigned byte order for deterministic classification. Only valid UTF-8 canonical basenames may appear in result metadata. An invalid basename is counted in its component's `source_count` and `sources_omitted_count` but its raw bytes are never emitted; its raw bytes and digest still participate in immutable proof and source identity.

Consequences:

- Arbitrary filenames are not supported by directory discovery. A selected `.jsonl` with a mismatching stem is isolated and reported; it is not silently ignored.
- Multiple runs in one directory file are not supported and isolate that component.
- A run split across files is not supported. Every file claiming the repeated run or trace identity is isolated; no filename-ordered winner is selected.
- Normal/private copies with the same stem conflict in a mixed authorized grant and both are isolated.
- Explicit `TraceLog` single-file grants remain filename-agnostic and may contain multiple complete, disjoint runs. They do not combine with sibling files. Exact selected-run capture remains one selected command run and still requires embedded identity to match its selector.
- Non-`.jsonl` files and `.ptcins` inspection artifacts are outside trace admission. The reserved private suffix continues to determine source class.

This removes the ordinary/capture divergence and makes removal of one bad file incapable of leaving an admitted partial run.

## Deterministic admission and isolation algorithm

The implementation must have one shared directory-admission result used transiently by direct directory queries and retained by snapshots.

1. **Bound and select.** List at most 4,096 entries. From that bounded listing select the grant-visible suffixes, then sort raw basenames by unsigned byte order. Sanitized grants select normal `.jsonl`; private-only grants select `.private.jsonl`; mixed private-authorized grants select both. Count and report the opposite class exactly as today, without names.
2. **Inventory before reading.** Reject the whole source if selected-file count exceeds 1,024 or the sum of inventoried regular selected-file sizes exceeds the aggregate source-byte ceiling. The sum includes files later isolated. This happens before reading, so no order-dependent prefix can be admitted.
3. **Prove a stable capture.** Bind the directory root by `{major_device, minor_device, inode, type}` only; directory mode, size, mtime, and ctime are not selected-source identity because excluded-class activity changes them. Repeat the bounded full listing, filter it to the grant-selected raw name set, and compare that selected set plus every selected file's lstat identity, exact size, and bytes around decode. Open selected files without following non-regular members. Direct directory queries perform this same transient immutable admission on every query. Root replacement or a selected member/name that appears, disappears, changes type/identity/metadata/content, or changes during failed-read verification rejects the entire source as `:source_changed`; mutation is never isolation.
4. **Build bounded file evidence.** Each selected raw basename is one node. Derive a filename run claim only when the basename satisfies the canonical grammar above. If every JSONL row decodes, collect every bounded binary embedded run and trace claim before semantic validation. If JSONL syntax is malformed, do not use a decoded prefix; retain only a valid filename run claim.
5. **Assign local reasons.** Use the closed reason vocabulary and precedence below. A fully decoded file may carry more than one applicable reason. JSON syntax failure/empty input stops semantic classification for that file; unsupported-version rows are not additionally called malformed merely for that version.
6. **Connect dependencies.** Add an undirected edge between files sharing any filename or embedded run claim, or any embedded trace claim. Compute transitive connected components. Add `run_identity_conflict` to every component in which one run claim is held by multiple files. Add `trace_identity_conflict` when one trace claim occurs in multiple files or maps to multiple run claims.
7. **Admit or isolate.** A component is admitted only when it is exactly one regular/readable file with zero reasons, one embedded run, one embedded trace, a matching filename stem, and existing event/sequence/lifecycle validation succeeds. Otherwise isolate every file and every claimed identity in the component. Never deduplicate, merge, repair, or select a winner.
8. **Order results.** Order components by their sorted source-name vector; order sources by basename; order reasons by the fixed vocabulary below. Existing admitted-run ordering remains start time descending with run ID as tie-breaker.

Closed isolation reasons, in order:

1. `invalid_filename` — the suffix-selected basename does not satisfy the canonical basename grammar.
2. `not_regular` — selected basename is a symlink or another non-regular type.
3. `unreadable` — a stable selected regular file cannot be read after re-verification.
4. `malformed_jsonl` — empty file, invalid JSONL, duplicate JSON keys, or non-object row.
5. `unsupported_version` — a decoded event has a schema version other than the supported version.
6. `filename_run_mismatch` — zero or multiple embedded run IDs, or the unique embedded run ID differs from a valid filename stem.
7. `run_identity_conflict` — a run claim participates in more than one file.
8. `trace_identity_conflict` — a file has multiple trace IDs, or a trace claim occurs in multiple files or maps to multiple runs.
9. `sequence_conflict` — the existing positive, strictly increasing trace-sequence contract fails.
10. `lifecycle_conflict` — the existing run/evaluation lifecycle contract fails.
11. `malformed_event` — any other envelope, timestamp, event-data, current-field, or producer-grade validation fails.

For `unreadable`, failure is isolatable only when repeated inventory proves the same static regular file and selected source. Any ambiguity is `:source_changed` or `:source_unavailable`, not quarantine.

## Limits and failure table

No new per-file limit is added. The 8,000,000-byte aggregate ceiling already bounds one file, selected-file capture uses that same ceiling, and canonical producers may legitimately approach it. A lower per-file ceiling would create an unevidenced incompatibility without improving the aggregate bound.

| Condition | Scope/result |
| --- | --- |
| Stable malformed/non-regular/unreadable file, unsupported schema, filename mismatch, identity, sequence, or lifecycle conflict | Isolate the full connected component; admit disjoint healthy components |
| More than 4,096 directory entries | Reject whole source: `:source_limit_exceeded` |
| More than 1,024 grant-selected trace files | Reject whole source: `:source_limit_exceeded` |
| Sum of all selected regular file sizes above configured aggregate (default/hard max 8,000,000) | Reject whole source: `:source_limit_exceeded` |
| Decoded retained admission above 32,000,000 bytes or admission heap exhaustion | Reject whole source: existing `:source_retained_limit_exceeded` form |
| Directory listing/root unavailable, admission deadline, or unclassifiable I/O failure | Reject whole source: `:source_unavailable` |
| Selected name/root/file mutation during inventory/read/verification | Reject whole source: `:source_changed` |
| Query result cannot fit after the metadata rules below | Existing `:result_limit_exceeded` |
| Mutation only in a suffix class excluded by the grant, while every repeated full listing remains within 4,096 entries | Does not alter selected source identity/cursor; the final successful listing supplies the advisory exclusion count |
| Exact selected-run file malformed/oversized/changed | Existing selected-source error; unrelated files remain ignored |

Directory-backed direct `TraceLog` and `TraceSnapshot` must share the 4,096/1,024/8,000,000/32,000,000/1,000,000 defaults and hard maxima. Hosts/tests may lower construction limits but not raise them. Add the missing directory/file/retained construction bounds to direct directory loading; keep file-count and directory-entry limits inapplicable to explicit single-file and exact selected sources.

### Namespace mutation and excluded classes

Every inventory/verification listing is bounded against all directory entries. If any repeated listing exceeds 4,096 entries, the result is whole-source `:source_limit_exceeded`, even when the crossing entry has an excluded suffix. Otherwise, compare only the grant-selected raw name set. Excluded-only additions, removals, or content changes may change directory timestamps and the advisory exclusion count but do not produce `:source_changed` and do not enter source identity. The final successful bounded listing supplies the stored exclusion count. Replacing the directory root's device/inode/type, or changing the selected name set or any selected file proof, remains whole-source `:source_changed` after initial admission; inability to establish the initial root/listing remains `:source_unavailable`.

### Exact retained-size accounting and errors

The shared classifier constructs one immutable `directory_admission_v1` value containing the grant class, selected raw-name proofs and digests, admitted events, per-run provenance, compiled analysis projection, complete isolation components/claims/reasons, source identity, source/file byte counts, and advisory exclusion metadata. After detaching sub-binaries, charge `PtcRunner.Lisp.RetainedSize.bytes/1` over that entire value. Owner/process bookkeeping, query arguments, cursors, and presentation-time fitted examples are not part of the retained admission charge. Direct transient admission and snapshots must measure the byte-identical value with the same 32,000,000-byte ceiling.

A measured value above the ceiling or an `:oversized`/admission-heap outcome is internally `:source_retained_limit_exceeded`. Public surfaces are fixed as follows:

- direct `TraceLog.query/3` returns `{:error, :source_retained_limit_exceeded}` so its existing atom-only error contract remains closed;
- `TraceSnapshot.start/2` retains its existing detailed tuple when measurement completes: `{:source_retained_limit_exceeded, %{source: :ptc_trace_snapshot | :ptc_private_trace_snapshot, measured_bytes: B, limit_bytes: L}}`; an unmeasurable/heap-killed capture retains the existing atom form;
- Viewer maps the direct atom to HTTP 413 with body `Trace source retained size exceeded`;
- host analysis construction continues to map the snapshot tuple/atom through its existing local-preflight environment-unavailable diagnostic.

## Visible bounded isolation metadata

`:list_runs` (every page) and `:counters` return the same source-level `"isolation"` object when at least one component is isolated. The field is absent when none is isolated. It is independent of filters and pagination.

```json
{
  "isolation": {
    "component_count": 2,
    "source_count": 3,
    "known_run_count": 2,
    "reasons": [
      {
        "reason": "malformed_jsonl",
        "component_count": 1,
        "source_count": 1
      },
      {
        "reason": "run_identity_conflict",
        "component_count": 1,
        "source_count": 2
      }
    ],
    "examples": [
      {
        "sources": ["broken.jsonl"],
        "source_count": 1,
        "sources_omitted_count": 0,
        "reasons": ["malformed_jsonl"]
      },
      {
        "sources": ["same.jsonl", "same.private.jsonl"],
        "source_count": 2,
        "sources_omitted_count": 0,
        "reasons": ["run_identity_conflict"]
      }
    ],
    "examples_omitted_count": 0
  }
}
```

Rules:

- Totals and per-reason counts are exact. A component with multiple reasons contributes once to each applicable reason, so reason counts need not sum to `component_count`.
- `known_run_count` is the exact distinct set of grant-visible filename and fully decoded embedded run claims in isolated components.
- At most 16 component examples and at most 8 sorted source basenames per example are returned. Omission counts are exact.
- `sources` are grant-relative, valid canonical UTF-8 basenames only—never absolute paths. Invalid raw basenames are counted but omitted as defined by the basename grammar. A normal grant never exposes private basenames or private run claims; a private-only grant never exposes sanitized basenames; a mixed private-authorized grant may expose both. Opposite-class files retain the existing count-only `excluded_*_trace_files` fields and never enter `isolation`.
- `omitted_count` and `truncated` keep their existing pagination-only meaning. Isolation is not pagination omission.
- Hard-capped examples are diagnostic, not identity authority. Before fitting run items, drop example sources/components from the deterministic tail as needed and increase the corresponding omission counts. Exact totals and reason counts are never dropped. Then apply the existing largest-item-prefix page algorithm. If the fixed result plus exact isolation summary cannot fit, return `:result_limit_exceeded`.
- Counters similarly drop diagnostic examples first; the counter aggregate itself is never truncated.

Run-scoped behavior:

- `:get_run` and `:list_turns` return `{:error, :run_isolated}` when the requested ID is a grant-visible filename or embedded run claim in an isolated component.
- They return `{:error, :not_found}` when the ID is neither admitted nor known isolated in that grant. Thus a normal query for a private or otherwise out-of-grant name remains indistinguishable from absence.
- Run-scoped successes do not carry directory-wide isolation metadata. `:list_runs` with a run filter and `:counters` continue to operate over admitted runs and carry the source-level isolation summary.

Public `:run_isolated` mappings are closed:

- raw `TraceLog` / `TraceSnapshot` queries return `{:error, :run_isolated}`;
- `RunAnalysisCapability` maps it to non-retryable `ProviderError{kind: :unavailable, details: "analysis run is isolated by damaged trace evidence"}`;
- Viewer kernel routes return HTTP 422 with the exact plain-text body `run_isolated`;
- `PtcViewer.Api` and `ViewerAdapter` preserve the atom unchanged and do not translate it to `:not_found`, `:invalid_query`, or an adapter failure.

## Source identity, cursors, and snapshots

Define one `directory_admission_v1` source identity over:

- the grant class;
- the sorted selected raw relative-name bytes (including invalid names), source classes, byte lengths, and content digests;
- each file's complete classification/claims;
- the admitted canonical events and per-run source provenance;
- the complete untruncated isolation components and reasons.

It must not contain or commit to absolute paths, opposite-class basenames/bytes, the advisory opposite-class exclusion count, presentation example caps, or capture time.

Consequences:

- Any selected file becoming healthy, damaged, added, removed, or differently isolated changes direct-query source identity and makes an old cursor fail `:source_changed`.
- Isolation metadata does not enter the normalized query/filter identity separately; it participates through source identity.
- Snapshot `capture_id` / `snapshot_hash` derive from this identity, so an immutable snapshot and all its cursors remain stable after later disk changes.
- Result-byte removal of examples does not change source identity.
- Direct and snapshot results for the same proven admission differ only by snapshot metadata, as today.

## Consumer parity

The same admission result and classifier must feed:

- ordinary `TraceLog` directory queries;
- normal, private-only, and mixed private-authorized `TraceSnapshot` directory capture;
- all four primitive query operations;
- host run-analysis capabilities;
- Viewer directory discovery via `ViewerSnapshotStore`.

Viewer must display a bounded damaged-source notice from the shared `isolation` object and preserve the existing private/sanitized exclusion notice. It must not rescan, reinterpret, or authorize files itself.

#1578 continues to own when Viewer refreshes/captures and re-evaluates `viewer.private`. Its refresh must consume this admission result atomically: `:source_changed` or whole-source resource failure cannot be converted into a partial new Viewer snapshot. #1654 should land before the directory-refresh half of #1578; the request-time authorization half is independent.

Exact selected-run capture remains separate: it opens one canonical candidate, ignores unrelated damage and directory/file-count limits, proves embedded identity, and keeps #1653's selected source identity and errors.

## Implementation slices

Each slice must keep the suite green and update its owning retained docs/tests.

1. **Classifier foundation:** add the shared bounded inventory/file-evidence/component data types and pure deterministic classifier behind focused tests; keep consumers on current behavior.
2. **Immutable admission cutover:** make `capture_directory/2` produce `directory_admission_v1`, enforce canonical filename binding, limits, component isolation, mutation proof, and full source identity; update snapshot fixtures and snapshot/source-identity docs.
3. **Direct-query parity:** route ordinary directory `TraceLog` through the same transient admission, add its missing construction bounds, add `:run_isolated`, and prove byte-for-byte query parity apart from snapshot metadata.
4. **Metadata and Viewer:** add bounded result fitting/schema, capability/error mapping, Viewer notice/API tests, and update the demo to retain generated filename-bound traces.
5. **Contract cleanup:** replace remaining arbitrary/multi-run directory fixtures, update all retained CLI/Viewer/trace-contract references, run generated-doc/schema owners where affected, and delete obsolete permissive helpers rather than retaining a legacy path.

Do not copy classifier/loading helpers into a second module.

## Objectively testable acceptance criteria

- [ ] One valid filename-bound normal run remains queryable beside an unrelated malformed JSONL file in direct and snapshot paths.
- [ ] Empty, duplicate-key, invalid-JSON, non-object, unsupported-version, non-regular, and stably unreadable selected files receive the exact reason above without hiding disjoint healthy runs.
- [ ] Empty/overlong, separator/control-bearing, and invalid-UTF-8 suffix-selected basenames receive `invalid_filename`; raw unsafe bytes never reach JSON, logs, Viewer HTML, or diagnostics but do participate in counts, proof, ordering, and source identity.
- [ ] Filename mismatch and a multi-run file are isolated and visible; neither is admitted.
- [ ] A run split across two normal files, across normal/private files, or across a canonical and mismatched filename isolates every involved transitive component with no winner.
- [ ] One trace ID claimed by different runs/files isolates every involved component.
- [ ] Non-monotonic/duplicate sequence and run/evaluation lifecycle conflicts isolate only their connected component.
- [ ] Removing the bad file cannot reveal a partial admitted run because no split-run layout is supported.
- [ ] Explicit single-file aggregate loading still accepts multiple complete disjoint runs and documented arbitrary filenames; directory discovery does not.
- [ ] Normal, private-only, and mixed grants select the right classes; no result/error for a normal grant exposes a private basename or run claim.
- [ ] Opposite-class exclusion counts remain distinct from isolation and pagination omission.
- [ ] Entry-count, selected-file-count, aggregate-byte, retained-byte/heap, and result-byte boundaries pass exactly at the limit and fail above it with the table's scope.
- [ ] Retained accounting charges the complete detached `directory_admission_v1` value identically for direct and snapshot capture and exposes the exact direct/snapshot/Viewer errors specified above.
- [ ] Excluded-class changes below the entry ceiling alter only the final advisory exclusion count; selected changes/root replacement return `:source_changed`, and an excluded addition crossing 4,096 entries returns `:source_limit_exceeded`.
- [ ] Aggregate-byte exhaustion is computed before reads over all selected regular files and never admits a filename-ordered prefix.
- [ ] No additional per-file limit exists; exact selected files and directory files use the same aggregate ceiling authority.
- [ ] `list_runs` pages and `counters` return exact totals/reason counts, deterministic capped examples, and exact omission counts.
- [ ] Result fitting drops diagnostic examples deterministically before admitted items and returns `:result_limit_exceeded` when the fixed result cannot fit.
- [ ] Full isolation evidence changes source identity/cursors even when admitted runs are unchanged; presentation-only example truncation does not.
- [ ] Direct cursors return `:source_changed` after selected static evidence changes; snapshot cursors remain stable.
- [ ] `get_run` and `list_turns` distinguish admitted, grant-visible known-isolated, and absent/out-of-grant IDs exactly as specified; raw, capability, and Viewer mappings match the closed `:run_isolated` table.
- [ ] Direct and snapshot primitive queries agree apart from snapshot metadata; host capabilities and Viewer preserve that result.
- [ ] Exact selected-run capture still succeeds beside malformed/oversized unrelated files and still rejects mutation/ambiguity of its selected candidate.
- [ ] Selected directory/root/file mutation at every inventory/read/verification hook returns `:source_changed` for the whole source, never an isolation reason.
- [ ] Viewer renders shared bounded isolation evidence and does not own a second classifier; #1578 retains refresh and authorization ownership.
- [ ] `examples/viewer-demo` no longer renames canonical trace files away from their run IDs.
- [ ] Owning `TraceLog`/snapshot module docs, `docs/maintainers/trace-log-contract.md`, kernel/CLI/Viewer/project-file guidance, fixtures, and generated site/reference artifacts are updated with their owning generators.
- [ ] Focused tests cover deterministic ordering under reversed creation/listing order and every hard example/source cap.
- [ ] `mix precommit`, canonical core tests, Viewer tests, and warnings-as-errors ExDoc pass for the slices that touch them.

## Dependencies and non-goals

Dependencies: merged #1653 and parent #1650. #1655 is independent. #1578 should consume this result for its directory-refresh half but does not block implementation of this issue. #1605 continues to own structural validation of normal trace budgets.

Non-goals: automatic repair/deletion, silent deduplication, a legacy directory reader, manifests for split runs, arbitrary filesystem browsing, inspection-artifact admission, remote/mutable trace databases, Viewer refresh cadence, request-time authorization, active trace persistence/recovery, and changes to exact selected-run routing.

**Comment by andreasronge** [comment]
## Readiness review — 2026-08-26

**Verdict: not ready for implementation yet.** The failure mode, scope, consumers, and acceptance boundary are evidenced and sufficiently described, but two choices materially determine the design and tests:

1. **Canonical file/run rule.** Direct loading currently permits a run to span files; immutable capture rejects it. Isolation cannot prove that a decodable file contains a complete run when an unreadable arbitrary file may contain more events for the same identity. Choose either a canonical one-run/one-file rule (including filename binding/migration behavior) or a complete dependency/manifest mechanism.
2. **Admission/loss contract.** Freeze shared directory/file/per-file/aggregate limits and the exact bounded metadata/source-identity schema before code changes. Otherwise direct queries, snapshots, cursors, privacy grants, and Viewer can acquire incompatible meanings.

Recommended focused research:

- inventory repository fixtures, docs, and supported external trace layouts for split runs and arbitrary filenames;
- decide whether the 0.x contract should narrow to canonical `<run-ref>[.private].jsonl` files for isolating directory discovery;
- specify the deterministic component algorithm and a small result-schema example;
- verify that #1578 consumes this admission result without moving Viewer refresh/authorization ownership into this issue.

After those decisions are written into the issue, the suggested implementation slices are independently testable. Until then, retain `decision` and use `needs-maintainer-input`, not `ready-for-implementation`.

**Comment by andreasronge** [comment]
## Readiness review — 2026-08-26

**Verdict: ready for implementation.**

The issue now freezes every product decision that previously required maintainer input:

- canonical whole-directory discovery is one filename-bound run/trace per file; arbitrary names, multi-run files, and split runs are isolated, while explicit single-file aggregates and #1653's exact selected-run path remain separate;
- one deterministic file/run/trace claim graph isolates the full transitive component, with a closed ordered reason vocabulary and no winner selection;
- directory-entry, file-count, aggregate-source, retained, and result limits have exact whole-source/component behavior, and no additional per-file limit is introduced;
- `list_runs` / `counters` metadata, privacy-safe source names, result fitting, source identity, cursors, snapshots, and `:run_isolated` behavior are specified exactly;
- direct queries, snapshots, grant classes, host capabilities, and Viewer discovery must consume the same admission result;
- source mutation remains whole-source `:source_changed`; #1578 retains refresh and authorization ownership.

Repository evidence supports the narrowing: every directory producer and retained artifact-layout guide already uses `<run-id>[.private].jsonl`; the opposing layouts occur in convenience fixtures and the Viewer demo rename, not as a promised directory workflow. The documented arbitrary `trace.jsonl` REPL flow remains supported as an explicit single-file source.

No unresolved dependency blocks work. #1654 should land before #1578's directory-refresh half so refresh consumes the shared admission result; #1578's request-time authorization half and #1655 are independent. The implementation slices and acceptance checks are small and objective enough to begin without further product decisions.

**Comment by andreasronge** [comment]
## Final contract-resolution review — 2026-08-26

**Verdict: ready for implementation.** The four gaps from the follow-up audit are now closed:

- directory basenames use a bounded ASCII canonical grammar; unsafe/invalid raw names receive `invalid_filename`, remain part of proof and counts, and never enter JSON/UI diagnostics;
- root proof is device/inode/type plus repeated grant-filtered name/file proof, so excluded-class changes below the directory-entry ceiling remain advisory while selected changes and root replacement are `:source_changed`;
- raw queries, Run Analysis, Viewer adapters, and HTTP routes have exact distinct `:run_isolated` mappings;
- direct and snapshot paths charge the same complete detached `directory_admission_v1` value, with exact atom/tuple/HTTP retained-limit behavior.

The final body contains no remaining product choice for an implementer. Its classifier-first slices are independently landable, #1653 is merged, #1655 is independent, and only #1578's directory-refresh half is ordered after this shared admission contract. Retain `ready-for-implementation`; no `decision` or `needs-maintainer-input` label is warranted.

**Comment by andreasronge** [comment]
Claimed by an agent working in `codex/issue-1654-directory-admission` at `/Users/andreasronge/projects/ptc_runner-codex-issue-1654-directory-admission` on Andreass-MacBook-Pro, 2026-08-26T10:31:39Z.

Assignment here is advisory, not a lock. If this claim has no commits on `codex/issue-1654-directory-admission` and has gone quiet, unassign and take it over.
